### ISSUE TITLE
Can't found -lcryptopp

### ISSUE THREAD

**Issue by dickfala** [SandeepAggarwal/CryptoppECC#5]
Hi, I download the project to test,
I create Podfile in the ExampleApp folder. and add the pod "CryptoppECC" in the Podfile.
Then I using pod install , open the "cryptoppdemo.xcworkspace" to build the project.
It will show below message error.
ld: library not found for -lcryptopp clang: error: linker command failed with exit code 1 (use -v to see invocation)
Should I set something  in the project to achieve the project  build success?
Thank you very much.

**Comment by SandeepAggarwal** [comment]
Hi,

I have made some changes to the ExampleApp. Please try to download/clone it again and run 
'pod install' in  `ExampleApp` directory.

And please make sure to set `Build Active Architecture Only` to `NO `for 'Pods' project and app's target

Let me know if u have any other problems.

Thanks.

**Comment by dickfala** [comment]
Hi,
How can I use the code generate public/private/encrypted message result in the ".m" File(Or in .m file using the .mm property), 
In the .m file use the result can do more function in the app.
Thank you very much.

**Comment by SandeepAggarwal** [comment]
Hi, 
You have to use the .mm file otherwise it won't compile.
Btw, you can do everything in .mm file exactly which u can do in .m file.

**Comment by wwwang89** [comment]
oh. no ,when I download the project ,and pod install, the same error occurred，
ld: library not found for -lcryptopp
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I use xcode9.4， any help ？

**Comment by wwwang89** [comment]
@dickfala hello ，how did u solve the problem ？ can u support  the right project ？3Q
